// Generated by https://quicktype.io

export interface PokemosListName {
    count: number;
    next: string;
    previous: null;
    results: PokemonName[];
}

export interface PokemonName {
    name: string;
    url: string;
}
